version: "2"
run:
  tests: true
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - revive
  settings:
    errcheck:
      check-type-assertions: true
  exclusions:
    generated: lax
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 5
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
