name: PR Validation

on:
  pull_request:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run Linter
        run: make lint

      - name: Run Unit Tests
        run: make test

      - name: Run E2E Tests
        run: make e2e
