name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Install golangci-lint 2.1.6
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.1.6/golangci-lint-2.1.6-linux-amd64.tar.gz -o linter.tar.gz
          mkdir -p tmp-linter
          tar -xzf linter.tar.gz -C tmp-linter
          sudo mv tmp-linter/golangci-lint-2.1.6-linux-amd64/golangci-lint /usr/local/bin/

      - name: Run Linter
        run: make lint

      - name: Run Unit Tests
        run: make test

      - name: Run E2E Tests
        run: make e2e

      - name: Generate coverage profile
        run: go test -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out

      - name: Install Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          install-only: true

      - name: Run Goreleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

